name: Windows - Run TestSearchFunction

on:
  push:
    branches: [ "main", "dev", "feature/**", "release" ]
  pull_request:
    branches: [ "main", "dev", "release" ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore (TestCore only)
        run: dotnet restore .\TestCore\TestCore.csproj

      - name: Test (TestCore only)
        run: dotnet test .\TestCore\TestCore.csproj
