name: Windows - Run TestSearchFunction

on:
  push:
    branches: [ main, dev, feature/** ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore (TestCore only)
        run: dotnet restore .\TestCore\TestCore.csproj

      - name: Build (TestCore only)
        run: dotnet build .\TestCore\TestCore.csproj --configuration Release --no-restore
